namespace MinimalApiAutoRepr.Generators;

using Microsoft.CodeAnalysis;

[Generator]
public class EndpointInterfaceGenerator : IIncrementalGenerator
{
    private const string InterfaceSource =
        """
        // <auto-generated>
        namespace MinimalApiAutoRepr.Generated;
        public interface IEndpoint
        {
            public static abstract void Map(IEndpointRouteBuilder app);
        }

        public interface IGroupEndpoint
        {
            public static abstract IEndpointRouteBuilder Map(IEndpointRouteBuilder app);
        }

        public interface IGroupEndpoint<TParentGroup> : IGroupEndpoint where TParentGroup : IGroupEndpoint
        {
        }

        public interface IEndpoint<TGroup> : IEndpoint where TGroup : IGroupEndpoint
        {
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("IEndpoint.g.cs", InterfaceSource);
        });
    }
}

