using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MinimalApiAutoRepr.Generators;

[Generator]
public class EndpointMapperGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
				transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
			.Where(static s => s != null)!
			.Select(static (s, _) => s!);

		var compilationAndTypes = context.CompilationProvider.Combine(provider.Collect());

		context.RegisterSourceOutput(compilationAndTypes, (spc, source) => Generate(spc, source.Left, source.Right));
	}

	static void Generate(SourceProductionContext spc, Compilation compilation, object typesObj)
	{
		var groups = new List<GroupInfo>();
		var endpoints = new List<EndpointInfo>();

		if (typesObj is IEnumerable<INamedTypeSymbol> types)
		{
			ParseTypes(types, groups, endpoints);
		}
		else
		{
			// fallback: nothing to parse
		}

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("using System;");
		sb.AppendLine("using Microsoft.AspNetCore.Builder;");
		sb.AppendLine("using Microsoft.AspNetCore.Routing;");
		sb.AppendLine();
		sb.AppendLine("namespace MinimalApiAutoRepr.Generated");
		sb.AppendLine("{");
		sb.AppendLine("    public static class GeneratedEndpointMappings");
		sb.AppendLine("    {");
		sb.AppendLine("        public static IEndpointRouteBuilder MapAutoReprEndpoints(this IEndpointRouteBuilder app)");
		sb.AppendLine("        {");

		var groupBySymbol = groups.ToDictionary(g => (ISymbol)g.Symbol, SymbolEqualityComparer.Default);
		var children = BuildChildrenMap(groups);

		ReportCyclesIfAny(spc, groups, children, groupBySymbol);

		var endpointRouteBuilderSymbol = compilation.GetTypeByMetadataName("Microsoft.AspNetCore.Builder.IEndpointRouteBuilder")
			?? compilation.GetTypeByMetadataName("Microsoft.AspNetCore.Routing.IEndpointRouteBuilder");
		var routeGroupBuilderSymbol = compilation.GetTypeByMetadataName("Microsoft.AspNetCore.Builder.RouteGroupBuilder")
			?? compilation.GetTypeByMetadataName("Microsoft.AspNetCore.Routing.RouteGroupBuilder");

		var groupVarByType = EmitGroups(sb, groups, children, groupBySymbol, endpointRouteBuilderSymbol, routeGroupBuilderSymbol);

		EmitEndpoints(sb, endpoints, groups, groupVarByType);

		sb.AppendLine("            return app;");
		sb.AppendLine("        }");
		sb.AppendLine("    }");
		sb.AppendLine("}");

		spc.AddSource("GeneratedEndpointMappings.g.cs", sb.ToString());
	}

	static void ParseTypes(IEnumerable<INamedTypeSymbol> types, List<GroupInfo> groups, List<EndpointInfo> endpoints)
	{
		foreach (var symbol in types)
		{
			foreach (var attr in symbol.GetAttributes())
			{
				var attrName = attr.AttributeClass?.Name;
				if (attrName == null)
				{
					continue;
				}

				if (attrName == "MapGroupAttribute")
				{
					var prefix = attr.ConstructorArguments.Length > 0 ? attr.ConstructorArguments[0].Value as string : null;
					var name = GetAttributeStringArgument(attr, 1);
					var parent = GetAttributeTypeArgument(attr, 2);
					var summary = GetAttributeNamedString(attr, "Summary");
					var description = GetAttributeNamedString(attr, "Description");
					groups.Add(new GroupInfo(symbol, prefix ?? string.Empty, name, summary, description, parent));
				}

				if (attrName == "MapGetAttribute" || attrName == "MapPostAttribute" || attrName == "MapPutAttribute" || attrName == "MapDeleteAttribute" || attrName == "MapPatchAttribute")
				{
					var method = symbol.GetMembers().OfType<IMethodSymbol>().FirstOrDefault(m => m.Name == "Handle" && m.IsStatic);
					if (method == null)
					{
						break;
					}

					var httpMethod = attrName.Replace("Map", string.Empty).Replace("Attribute", string.Empty);
					var route = attr.ConstructorArguments.Length > 0 ? attr.ConstructorArguments[0].Value as string : null;
					var name = GetAttributeStringArgument(attr, 1);
					var groupType = GetAttributeTypeArgument(attr, 2);
					var summary = GetAttributeNamedString(attr, "Summary");
					var description = GetAttributeNamedString(attr, "Description");

					endpoints.Add(new EndpointInfo(symbol, method, httpMethod, route ?? string.Empty, name, summary, description, groupType));
				}
			}
		}
	}

	static Dictionary<ISymbol, List<ISymbol>> BuildChildrenMap(List<GroupInfo> groups)
	{
		var children = new Dictionary<ISymbol, List<ISymbol>>(SymbolEqualityComparer.Default);
		foreach (var g in groups)
		{
			if (g.Parent != null)
			{
				if (!children.TryGetValue(g.Parent, out var list))
				{
					list = new List<ISymbol>();
					children[g.Parent] = list;
				}
				list.Add(g.Symbol);
			}
		}
		return children;
	}

	static void ReportCyclesIfAny(SourceProductionContext spc, List<GroupInfo> groups, Dictionary<ISymbol, List<ISymbol>> children, Dictionary<ISymbol, GroupInfo> groupBySymbol)
	{
		var indegree = new Dictionary<ISymbol, int>(SymbolEqualityComparer.Default);
		foreach (var g in groups)
		{
			indegree[g.Symbol] = 0;
		}

		foreach (var g in groups)
		{
			if (g.Parent != null && indegree.ContainsKey(g.Symbol) && groupBySymbol.ContainsKey(g.Parent))
			{
				indegree[g.Symbol]++;
			}
		}

		var checkQueue = new Queue<ISymbol>(indegree.Where(kv => kv.Value == 0).Select(kv => kv.Key));
		int processed = 0;
		while (checkQueue.Count > 0)
		{
			var s = checkQueue.Dequeue();
			processed++;
			if (children.TryGetValue(s, out var ch))
			{
				foreach (var c in ch)
				{
					indegree[c]--;
					if (indegree[c] == 0)
					{
						checkQueue.Enqueue(c);
					}
				}
			}
		}

		if (processed != groups.Count)
		{
			var cycleNodes = indegree.Where(kv => kv.Value > 0).Select(kv => kv.Key).ToList();
			var diagDesc = new DiagnosticDescriptor(
				"MAAR001",
				"MapGroup parent cycle",
				"MapGroup parent cycle detected for group '{0}' - cyclic parent references among MapGroup attributes",
				"Generator",
				DiagnosticSeverity.Warning,
				true);
			foreach (var sym in cycleNodes)
			{
				spc.ReportDiagnostic(Diagnostic.Create(diagDesc, Location.None, sym.ToDisplayString()));
			}
		}
	}

	static Dictionary<ISymbol, string> EmitGroups(StringBuilder sb, List<GroupInfo> groups, Dictionary<ISymbol, List<ISymbol>> children, Dictionary<ISymbol, GroupInfo> groupBySymbol, ISymbol? endpointRouteBuilderSymbol, ISymbol? routeGroupBuilderSymbol)
	{
		var groupVarByType = new Dictionary<ISymbol, string>(SymbolEqualityComparer.Default);
		int gi = 0;

		var emitted = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
		var parentVarBySymbol = new Dictionary<ISymbol, string>(SymbolEqualityComparer.Default);
		var q = new Queue<ISymbol>();

		foreach (var g in groups.Where(g => g.Parent == null))
		{
			parentVarBySymbol[g.Symbol] = "app";
			q.Enqueue(g.Symbol);
		}

		while (q.Count > 0)
		{
			var symbol = q.Dequeue();
			if (emitted.Contains(symbol))
			{
				continue;
			}

			if (!groupBySymbol.TryGetValue(symbol, out var ginfo))
			{
				continue;
			}

			var parentVar = parentVarBySymbol.TryGetValue(symbol, out var pv) ? pv : "app";

			var baseName = ToCamelCase(symbol.Name ?? ("group" + (++gi)));
			var varName = baseName;
			var suffix = 1;
			while (groupVarByType.Values.Contains(varName))
			{
				varName = baseName + (++suffix).ToString();
			}

			groupVarByType[symbol] = varName;

			var mapStart = $"{parentVar}.MapGroup(\"{EscapeString(ginfo.Prefix)}\")";
			var groupExts = new List<string>();
			if (!string.IsNullOrEmpty(ginfo.Name))
			{
				groupExts.Add($"WithName(\"{EscapeString(ginfo.Name!)}\")");
			}

			if (!string.IsNullOrEmpty(ginfo.Summary))
			{
				groupExts.Add($"WithSummary(\"{EscapeString(ginfo.Summary!)}\")");
			}

			if (!string.IsNullOrEmpty(ginfo.Description))
			{
				groupExts.Add($"WithDescription(\"{EscapeString(ginfo.Description!)}\")");
			}

			if (groupExts.Count == 0)
			{
				sb.AppendLine($"            var {varName} = {mapStart};");
			}
			else
			{
				sb.AppendLine($"            var {varName} = {mapStart}");
				for (int i = 0; i < groupExts.Count; i++)
				{
					sb.AppendLine("                ." + groupExts[i] + (i == groupExts.Count - 1 ? ";" : ""));
				}
			}

			if (routeGroupBuilderSymbol != null && symbol is INamedTypeSymbol ntsSymbol)
			{
				var mapMethod = ntsSymbol.GetMembers("Map").OfType<IMethodSymbol>()
					.FirstOrDefault(m => m.IsStatic && m.Parameters.Length == 1 &&
						SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, (ITypeSymbol)routeGroupBuilderSymbol) &&
						SymbolEqualityComparer.Default.Equals(m.ReturnType, (ITypeSymbol)routeGroupBuilderSymbol));
				if (mapMethod != null)
				{
					var containing = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
					sb.AppendLine($"            {containing}.Map({varName});");
				}
			}

			if (endpointRouteBuilderSymbol != null && symbol is INamedTypeSymbol ntsSymbol2)
			{
				var mapMethod = ntsSymbol2.GetMembers("Map").OfType<IMethodSymbol>()
					.FirstOrDefault(m => m.IsStatic && m.Parameters.Length == 1 &&
						SymbolEqualityComparer.Default.Equals(m.Parameters[0].Type, (ITypeSymbol)endpointRouteBuilderSymbol) &&
						SymbolEqualityComparer.Default.Equals(m.ReturnType, (ITypeSymbol)endpointRouteBuilderSymbol));
				if (mapMethod != null)
				{
					var containing = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
					sb.AppendLine($"            {containing}.Map(({endpointRouteBuilderSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}){varName});");
				}
			}

			emitted.Add(symbol);

			if (children.TryGetValue(symbol, out var childList))
			{
				foreach (var childSym in childList)
				{
					if (!parentVarBySymbol.ContainsKey(childSym))
					{
						parentVarBySymbol[childSym] = varName;
					}

					q.Enqueue(childSym);
				}
			}
		}

		return groupVarByType;
	}

	static void EmitEndpoints(StringBuilder sb, List<EndpointInfo> endpoints, List<GroupInfo> groups, Dictionary<ISymbol, string> groupVarByType)
	{
		foreach (var ep in endpoints)
		{
			var target = "app";
			if (ep.GroupType != null)
			{
				var groupSym = groups.Select(x => x.Symbol).FirstOrDefault(s => SymbolEqualityComparer.Default.Equals(s, ep.GroupType));
				if (groupSym != null && groupVarByType.TryGetValue(groupSym, out var gv))
				{
					target = gv;
				}
			}

			var method = ep.HttpMethod;
			var route = EscapeString(ep.Route ?? string.Empty);
			var containing = ep.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			var mapStart = $"{target}.Map{method}(\"{route}\", {containing}.Handle)";

			var extensions = new List<string>();
			if (!string.IsNullOrEmpty(ep.Name))
			{
				extensions.Add($"WithName(\"{EscapeString(ep.Name!)}\")");
			}

			if (!string.IsNullOrEmpty(ep.Summary))
			{
				extensions.Add($"WithSummary(\"{EscapeString(ep.Summary!)}\")");
			}

			if (!string.IsNullOrEmpty(ep.Description))
			{
				extensions.Add($"WithDescription(\"{EscapeString(ep.Description!)}\")");
			}

			if (extensions.Count == 0)
			{
				sb.AppendLine("            " + mapStart + ";");
			}
			else
			{
				sb.AppendLine("            " + mapStart);
				for (int i = 0; i < extensions.Count; i++)
				{
					sb.AppendLine("                ." + extensions[i] + (i == extensions.Count - 1 ? ";" : ""));
				}
			}
		}
	}

	static string GetAttributeStringArgument(AttributeData attr, int index)
	{
		if (attr.ConstructorArguments.Length > index)
		{
			var val = attr.ConstructorArguments[index].Value as string;
			return val ?? string.Empty;
		}


		// Check named arguments case-insensitively for common keys
		foreach (var named in attr.NamedArguments)
		{
			if (string.Equals(named.Key, "Name", StringComparison.OrdinalIgnoreCase) || string.Equals(named.Key, "name", StringComparison.OrdinalIgnoreCase))
			{
				return named.Value.Value as string ?? string.Empty;
			}
		}

		return string.Empty;
	}

	static string GetAttributeNamedString(AttributeData attr, string key)
	{
		foreach (var named in attr.NamedArguments)
		{
			if (string.Equals(named.Key, key, StringComparison.OrdinalIgnoreCase))
			{
				return named.Value.Value as string ?? string.Empty;
			}
		}

		return string.Empty;
	}

	static INamedTypeSymbol? GetAttributeTypeArgument(AttributeData attr, int index)
	{
		if (attr.ConstructorArguments.Length > index)
		{
			var typed = attr.ConstructorArguments[index];
			if (typed.Kind == TypedConstantKind.Type && typed.Value is INamedTypeSymbol nts)
			{
				return nts;
			}
		}

		foreach (var named in attr.NamedArguments)
		{
			if (named.Key == "Group" && named.Value.Kind == TypedConstantKind.Type && named.Value.Value is INamedTypeSymbol n2)
			{
				return n2;
			}
		}

		return null;
	}

	static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

	static string ToCamelCase(string s)
	{
		if (string.IsNullOrEmpty(s))
		{
			return s;
		}

		if (s.Length == 1)
		{
			return char.ToLowerInvariant(s[0]).ToString();
		}

		return char.ToLowerInvariant(s[0]) + s.Substring(1);
	}

	static string ToPascalCase(string s)
	{
		if (string.IsNullOrEmpty(s))
		{
			return s;
		}

		if (s.Length == 1)
		{
			return char.ToUpperInvariant(s[0]).ToString();
		}

		return char.ToUpperInvariant(s[0]) + s.Substring(1);
	}

	// Helper types (avoid C# record types to remain compatible with netstandard2.0)
	class GroupInfo
	{
		public INamedTypeSymbol Symbol { get; }
		public string Prefix { get; }
		public string? Name { get; }
		public string? Summary { get; }
		public string? Description { get; }
		public INamedTypeSymbol? Parent { get; }

		public GroupInfo(INamedTypeSymbol symbol, string prefix, string? name, string? summary, string? description, INamedTypeSymbol? parent)
		{
			this.Symbol = symbol;
			this.Prefix = prefix;
			this.Name = string.IsNullOrEmpty(name) ? null : name;
			this.Summary = string.IsNullOrEmpty(summary) ? null : summary;
			this.Description = string.IsNullOrEmpty(description) ? null : description;
			this.Parent = parent;
		}
	}

	class EndpointInfo
	{
		public INamedTypeSymbol Symbol { get; }
		public IMethodSymbol HandleMethod { get; }
		public string HttpMethod { get; }
		public string Route { get; }
		public string? Name { get; }
		public string? Summary { get; }
		public string? Description { get; }
		public INamedTypeSymbol? GroupType { get; }


		public EndpointInfo(INamedTypeSymbol symbol, IMethodSymbol handleMethod, string httpMethod, string route, string? name, string? summary, string? description, INamedTypeSymbol? groupType)
		{
			this.Symbol = symbol;
			this.HandleMethod = handleMethod;
			this.HttpMethod = httpMethod;
			this.Route = route;
			this.Name = name;
			this.Summary = string.IsNullOrEmpty(summary) ? null : summary;
			this.Description = string.IsNullOrEmpty(description) ? null : description;
			this.GroupType = groupType;
		}
	}
}
